obj-$(CONFIG_VIDEO_IMX_IPU_COMMON)	+= imx-ipu.o
obj-$(CONFIG_VIDEO_IMX_IPU_SCALER)	+= imx-ipu-scaler.o
obj-$(CONFIG_MEDIA_IMX) += imx-media.o
obj-$(CONFIG_MEDIA_IMX_VIDEO_SWITCH) += imx-video-switch.o
obj-$(CONFIG_VIDEO_IMX_IPUV3_CSI)	+= imx-ipuv3-csi.o
obj-$(CONFIG_VIDEO_IMX_IPU_OVL)		+= imx-ipu-ovl.o
obj-$(CONFIG_VIDEO_IMX_IPU_VDIC)	+= imx-ipu-vdic.o
obj-$(CONFIG_VIDEO_IMX_IPU_VOUT)	+= imx-ipu-vout.o

